### ISSUE TITLE
Ability to (optionally) limit who can create events?

### ISSUE THREAD

**Issue by duckinator** [lowercasename/gathio#1]
Hosting a personal instance of gathio would make a lot more sense if you could limit who can create events. I have a rough idea of a way to do this without having to introduce user accounts:

1. Add a config option of some sort which includes a list of "event creator" email addresses.
2. If that option isn't specified, ignore continue as it does now. Otherwise, go to step 3.
3. Instead of showing the normal `/new/event/public` page, have a form to enter your email address and request an link that lets you create an event.
4. When that form is submitted: if the email is in the list, send a temporary link to create an event; otherwise, either show an error or pretend to succeed but don't send a link. (Also see the note below.)
5. The link allows the user to create an event. It'd probably make sense to have the link auto-expire.

**Note regarding \#4:** I've seen arguments that things like this should always pretend to succeed. I'm not entirely sure of the implications, so I won't try to make an argument either way. It can always be changed later on.

---

@lowercasename, would you be open to this functionality being added? If so, I can try to make a PR adding it. If I make a PR it'll probably be next week.

And if you're open to this kind of thing being added, lmk if you have any suggestions for a better way to approach it.

**Comment by lowercasename** [comment]
Hi! I think this is a great idea and I'm all for it. I suggest you may as well make use of the MongoDB database to store config information, unless you know of a good reason to do it otherwise.

Another way I can think of doing this is:

- On the `/new/event/public` page, have a clear message telling users that only certain email addresses can make events
- Maybe put the email address field at the top of the new event form rather than near the bottom where it is now
- When the new event form is submitted, save it to the database marked as 'draft' or 'staging' or similar
- If the user's email is one of the permitted emails, send them an email with a link to the event - when the page is first loaded, it's been 'verified' and becomes publically accessible.
- If it's not one of the permitted emails, send them an email saying that they're not allowed to make events, but also maybe send a link to a separate page which they can forward to a person with a permitted email who can input their email and verify that event _for_ the user.

This sounds more complicated that your system! I'm absolutely happy to go with your idea, you decide.

**Comment by duckinator** [comment]
I think a hybrid of those two approaches would actually be really nice:

- On `/new/event/public`, have a clear message telling users only certain email addresses can make event.
- Move the email address field to the top of the new event form.
- When the new event form is submitted, if it's a permitted email, send them an email with a link to the event; otherwise, don't send a link. (Same deal as \#4 in my original suggestion.)

I think this is probably the simplest approach of the 3. It also has the bonus of making the whitelist-based vs completely-public modes a lot more consistent, since it's always serving the same pages.

This leaves the issue of where to put the config, however. The main problem I see with storing it in the database is that it'd probably need a dedicated command-line tool for managing it.

Given that, to me it feels like a config file is probably easier to setup/update the list. If you know of a way to have it in the database without those complications, I'd be open to putting it in there, though!

---

@lowercasename what're your thoughts on my revised idea? :slightly_smiling_face:

**Comment by lowercasename** [comment]
I love that idea, great combination of the two!

And yes, now that I think about it, a simple (JSON? I’m fond of JSON) file would be by far the easiest to manage and not require any kind of backend system.

I’m excited for this feature, thank you for taking it on!


________________________________

**Comment by lowercasename** [comment]
Actually thinking about it more, probably YAML or TOML would be a better choice for a general-purpose config file, huh. I leave it in your hands!

**Comment by lowercasename** [comment]
Nope, no preferred library, that looks super. And definitely don't stress with getting this done!

**Comment by duckinator** [comment]
I'm bad at this whole "existing" thing, but this is definitely still on my list of things to do at some point. :sweat_smile:
