### ISSUE TITLE
The ics shows other events?

### ISSUE THREAD

**Issue by TylerLeonhardt** [lowercasename/gathio#58]
I noticed the ICS that you get when you export it has a bunch of other events in it (mine is test at the very bottom):
![Screenshot_20210206-201427~2.png](https://user-images.githubusercontent.com/2644648/107136452-24774700-68b8-11eb-80be-444c29779fbf.png)

Is that expected?

**Comment by lowercasename** [comment]
Haha, no!! I'll fix that ASAP.

On February 7, 2021, Kit La Touche <notifications@github.com> wrote:
> I noticed the ICS that you get when you export it has a bunch of other

> events in it (mine is test at the very bottom):
>  
>

> Is that expected?
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lowercasename/gathio/issues/58>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AANK3IG35GVPRWFT4HIS6FDS5YH4ZANCNFSM4XHAIS3Q>.

**Comment by lowercasename** [comment]
Thanks for spotting this - it's been fixed in https://github.com/lowercasename/gathio/commit/4c25ce5460325e02ec6badbc5e19fd94625c89be.

**Comment by TylerLeonhardt** [comment]
@lowercasename feel free to permanently delete this issue since it has user info (I probably shouldn't have included the image 😅)
