### ISSUE TITLE
Guest list erased 😲 on new user registration

### ISSUE THREAD

**Issue by evolverine** [lowercasename/gathio#74]
This is the second event where my guest list has been mostly* erased! It happened in the past two days, when I last checked it.

\* I and one other guest are still there, plus a new one. But there used to be eleven.

It seems to be related to a new user registering. The previous time it happened (late last week), a friend told me that he thought he "did something strange" on the site when trying to twister. When I checked, he was, indeed, registered, but everyone else except me had disappeared.

As you may imagine, this is quite distressing and causing me many issues with organising these events.

I'm happy to send you the links in private, if they can help with debugging.

**Comment by lowercasename** [comment]
Oh no! Yes, please send me those links to mail@raphaelkabo.com and I'll have a look as soon as I can.

**Comment by lowercasename** [comment]
I've worked out the bug, and it was... well, peculiar and bizarre, but ultimately the result of badly written code, so I'm very sorry for messing up your event and I hope you'll be able to recover those attendees!

1. Due to recent changes to the frontend, the JavaScript on event pages didn't run properly when the page wasn't in editing mode.
2. Because the JS didn't work, the removal password field for event attendees came up blank.
3. Because there wasn't any checking of that field, a bunch of attendees got saved to the database with a blank removal password.
4. When someone tried to remove themselves from the event, they left the removal password field blank... and _all_ the attendees with a blank removal password were deleted. :fearful:

**Comment by lowercasename** [comment]
This has been fixed in https://github.com/lowercasename/gathio/commit/01b9d0bcec8480b358f040ccf8b7d4b489156d11, please do let me know if you see any other bugs.

**Comment by evolverine** [comment]
Thank you very much for your work to fix this. I've asked people to re-register, and it's been all right so far 🙏
