### ISSUE TITLE
MongoError: E11000

### ISSUE THREAD

**Issue by Anyndil** [lowercasename/gathio#75]
On create of second event, submit returns:

`Database error, please try again :( - MongoError: E11000 duplicate key error collection: gathio.events index: attendees.removalPassword_1 dup key: { attendees.removalPassword: null }`

Occurring in multiple environments. Tried Docker. Tried native install on Ubuntu 22.04 LTS.

**Comment by kousu** [comment]
I'm seeing this too, every single time. It makes gath unusable :(

I tried on

* OS: Ubuntu 22.04
* `mongod`: 6.2.0-alpha-1589-g654aa51
* [mongodb driver](https://www.npmjs.com/package/mongodb): 3.7.3
* [`mongoose`](https://www.npmjs.com/package/mongoose): 5.13.13

([complete version details](https://github.com/lowercasename/gathio/files/9997717/versions22.04.txt))

and also on

* OS: Ubuntu 20.04
* `mongod`: v3.6.8
* [mongodb driver](https://www.npmjs.com/package/mongodb): 3.7.3
* [`mongoose`](https://www.npmjs.com/package/mongoose): 5.13.13

([complete version details](https://github.com/lowercasename/gathio/files/9997738/versions20.04.txt))

----

I tracked down part of the cause, it's these two lines:

https://github.com/lowercasename/gathio/blob/dc165eb935308a05272f5ed1b20e2d1527ef9eb9/models/Event.js#L19

https://github.com/lowercasename/gathio/blob/dc165eb935308a05272f5ed1b20e2d1527ef9eb9/models/Event.js#L24

simply erasing those creates a working event server.

I wonder how come @lowercasename's https://gath.io or @dariusk's https://events.friend.camp/ aren't affected by this?

I experimented a bit and it seems the bug only happens if the database starts out empty. Deleting those lines, creating an event, then readding them and restarting the server leaves the server functional. Perhaps `mongoose` is generating a schema that is stricter than Gathio expects, and those two deployments have the older schema?

**Comment by kousu** [comment]
@Anyndil, would you be up for sharing how you got `mongodb` installed on 22.04? I struggled for an entire afternoon to do it.

There's [no official package for 22.04 == `jammy`](https://packages.ubuntu.com/jammy/mongodb) because of [licensing concerns Debian/Ubuntu have](https://en.wikipedia.org/wiki/MongoDB#MongoDB_Community_Server_2), and the company's Community Edition also [hasn't made it out to 22.04 yet](https://www.mongodb.com/docs/manual/administration/production-notes/#std-label-prod-notes-recommended-platforms) -- there are a few packages like `mongodb-cli` and `mongodb-mongosh` [here on their `jammy` repo](https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/6.0/multiverse/binary-amd64/), but `mongodb-org` and `mongodb-database-server` aren't built yet and judging from [this](https://github.com/mongodb/mongo/commit/f2acf616a89e4e45b8c0572202c45b8e629fabc7) they only started working on it on August 26th, over a month after you. 

I ended up building it from source, which is why I have that weird version "6.2.0-alpha-1589-g654aa51". I was sure my franken-mongo was the cause of this error, until I tested 20.04, and then saw that you had been having it months ago.

**Comment by kousu** [comment]
Alright, I've posted my workaround at https://github.com/lowercasename/gathio/pull/80; can you take a look, @lowercasename ? Thanks! <3

**Comment by lowercasename** [comment]
Hi @kousu, we were working on this at exactly the same time! I've just pushed a change to the main branch which I believe fixes this without removing the uniqueness constraint. Could you see if the newest version in main works on your system?

**Comment by kousu** [comment]
Nice! Right away.

First, 

<details><summary>Wiping mongodb</summary>

```
root@public:~# systemctl stop gathio
root@public:~# systemctl stop mongod
root@public:~# rm /var/lib/mongodb/  # -> this was [tab] completed
.bash_history                          index-11--4698457076673489121.wt       index-18--4698457076673489121.wt       mongod.lock
collection-0--4698457076673489121.wt   index-12--4698457076673489121.wt       index-19--4698457076673489121.wt       sizeStorer.wt
collection-10--4698457076673489121.wt  index-13--4698457076673489121.wt       index-3--4698457076673489121.wt        storage.bson
collection-2--4698457076673489121.wt   index-14--4698457076673489121.wt       index-5--4698457076673489121.wt        WiredTiger
collection-4--4698457076673489121.wt   index-1--4698457076673489121.wt        index-6--4698457076673489121.wt        WiredTigerHS.wt
collection-7--4698457076673489121.wt   index-15--4698457076673489121.wt       index-9--4698457076673489121.wt        WiredTiger.lock
collection-8--4698457076673489121.wt   index-16--4698457076673489121.wt       journal/                               WiredTiger.turtle
diagnostic.data/                       index-17--4698457076673489121.wt       _mdb_catalog.wt                        WiredTiger.wt
root@public:~# rm -r /var/lib/mongodb/*
```

</details>

<details><summary>Updating gathio</summary>

```
gathio@public:~/gathio$ git branch
* master
gathio@public:~/gathio$ git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 13 (delta 7), reused 11 (delta 7), pack-reused 0
Unpacking objects: 100% (13/13), 6.78 KiB | 630.00 KiB/s, done.
From https://github.com/lowercasename/gathio
   dc165eb..256d6ef  master     -> origin/master
Updating dc165eb..256d6ef
Fast-forward
 activitypub.js    |   17 +-
 models/Event.js   |    4 +-
 package-lock.json | 2042 ++++++++++----------------------------------------------------------------------------------------------------------------------------------
 package.json      |    4 +-
 4 files changed, 154 insertions(+), 1913 deletions(-)
gathio@public:~/gathio$ rm -rf node_modules/
gathio@public:~/gathio$ npm install

added 422 packages, and audited 423 packages in 8s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
gathio@public:~/gathio$ git show HEAD
commit 256d6ef79ef2e843763b0450efcac71bd40d8368 (HEAD -> master, origin/master, origin/HEAD)
Merge: 2f8ac8a 35a91fc
Author: Raphael <raphaelkabo@gmail.com>
Date:   Sun Nov 13 18:54:36 2022 +0000

    Merge pull request #79 from dariusk/dariusk-fedifix
    
    Updating federation code to work with recent Mastodon
```

</details>

I should be honest, I've got this other small patch in, because I want to force TLS (and this was easier than remembering how to use iptables):

```diff
gathio@public:~/gathio$ git diff
diff --git a/start.js b/start.js
index 1a001d3..36e8bfe 100755
--- a/start.js
+++ b/start.js
@@ -27,6 +27,6 @@ const app = require('./app');
 
 global.appRoot = path.resolve(__dirname);
 
-const server = app.listen(port, () => {
+const server = app.listen(port, '127.0.0.1', () => {
   console.log(`Welcome to gathio! The app is now running on http://localhost:${server.address().port}`);
 });
```

```
root@public:~# systemctl start mongod
root@public:~# systemctl restart gathio
```

<details><summary>Running internally on port 8478</summary>

```
gathio@public:~/gathio$ netstat -nltp | grep node
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:8478          0.0.0.0:*               LISTEN      23662/node  
```

</details>

<details><summary>nginx config</summary>

```
root@public:~# cat /etc/nginx/sites-enabled/gathio.nginx 
upstream gathio {
    server 127.0.0.1:8478 max_fails=5 fail_timeout=60s;
}

# Enable SSL session caching for improved performance
ssl_session_cache shared:ssl_session_cache:10m;

server {
    server_name events.public.garden;

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    ssl_trusted_certificate   /etc/letsencrypt/live/events.public.garden/chain.pem;
    ssl_certificate           /etc/letsencrypt/live/events.public.garden/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/events.public.garden/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_prefer_server_ciphers off;
    # In case of an old server with an OpenSSL version of 1.0.2 or below,
    # leave only prime256v1 or comment out the following line.
    ssl_ecdh_curve X25519:prime256v1:secp384r1:secp521r1;
    ssl_stapling on;
    ssl_stapling_verify on;

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/activity+json application/atom+xml;

    # the nginx default is 1m, not enough for large media uploads
    client_max_body_size 16m;
    ignore_invalid_headers off;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass http://gathio;
    }
}
```

</details>

<details><summary>Index</summary>

![Screenshot_20221113_135902](https://user-images.githubusercontent.com/987487/201539377-d889ff82-3798-4fe5-9fb3-6799dc008c12.png)

</details>

<details><summary>Creating event #1</summary>

![Screenshot 2022-11-13 at 14-05-33 Public Garden Events](https://user-images.githubusercontent.com/987487/201539505-adf6e230-c488-4536-85b1-7fd8e017a41e.png)

![Screenshot 2022-11-13 at 14-05-53 Test 1 · Public Garden Events](https://user-images.githubusercontent.com/987487/201539518-9bf15ab3-3552-45bc-af1d-236cf5c36230.png)

</details>


<details><summary>Creating event #2</summary>

![Screenshot 2022-11-13 at 14-06-30 Public Garden Events](https://user-images.githubusercontent.com/987487/201539683-3aefa279-e787-4e74-8bd4-97d535a90119.png)

![Screenshot 2022-11-13 at 14-06-37 Test 2 · Public Garden Events](https://user-images.githubusercontent.com/987487/201539624-444530f2-64aa-4ca8-b5da-95ded6ec8189.png)

</details>


<details><summary>Creating event #3</summary>

![Screenshot 2022-11-13 at 14-07-11 Public Garden Events](https://user-images.githubusercontent.com/987487/201539625-c6b0999f-dc9f-498c-83ee-0b956e87b2ca.png)
![Screenshot 2022-11-13 at 14-07-17 Test 3 · Public Garden Events](https://user-images.githubusercontent.com/987487/201539627-5ca2f358-8bc4-4d12-9ad2-a6581edb6a40.png)

</details>


<details><summary>Creating event #4</summary>

![Screenshot 2022-11-13 at 14-07-52 Public Garden Events](https://user-images.githubusercontent.com/987487/201539629-a419afc9-5671-427c-94cc-adab2e2cceb5.png)

![Screenshot 2022-11-13 at 14-08-21 Test 4 · Public Garden Events](https://user-images.githubusercontent.com/987487/201539631-55974f4e-3221-4a54-bd99-f7052918535e.png)

</details>

So it seems like https://github.com/lowercasename/gathio/commit/e2690ab3399b7b65601561347bf740a6fed38fa7 fixed it! And getting rid of those npm vulnerability warnings is a nice bonus. Thanks so much @lowercasename :rocket: :rocket: :rabbit:

**Comment by lowercasename** [comment]
Really pleased to hear that - and yes, it was a bit of an oversight on my part compounded by the fact that it was working on the main site with that schema.

I'll close this issue now - feel free to open again if you see another bug around this!
